server:
  port: 6776

spring:
  application:
    name: Derived_Queries
  datasource:
    url: jdbc:postgresql://localhost:5432/Employee_Database
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    com.developer.soumya: TRACE